[font]
size = 12.0
normal = { family = "Ubuntu Mono Nerd Font", style = "Regular" }

[window]
opacity = 0.85
decorations = 'None'

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
chars = "\n"
key = "Return"
mods = "Shift"

